# Generated by Django 5.0.2 on 2024-03-03 10:47

from django.db import migrations
from django.conf import settings
import pandas as pd
import os
import logging


def load_initial_data(apps, schema_editor):
    print("\nStart of initial data migration, this may take some time...")
    question_model = apps.get_model('masteriqapp', 'Question')
    option_model = apps.get_model('masteriqapp', 'Option')
    category_model = apps.get_model('masteriqapp', 'Category')

    directory = settings.INIT_DATA_FOLDER
    print(directory)
    for filename in os.listdir(directory):
        f = os.path.join(directory, filename)
        if os.path.isfile(f) and filename.endswith(".csv"):
            df = pd.read_csv(f)
            category_name = filename[:-4].replace('-', ' ').title()
            category = category_model.objects.create(name=category_name)
            for row in df.index:
                if pd.isnull(df['A'][row]) or pd.isnull(df['B'][row]):
                    continue
                question = question_model.objects.create(text=df['Questions'][row], category=category)
                right_option_text = df['Correct'][row]
                option_model.objects.create(text=right_option_text, is_correct=True, question=question)

                for letter in ['A', 'B', 'C', 'D']:
                    if pd.isnull(df[letter][row]) or df[letter][row] == right_option_text:
                        continue
                    option_model.objects.create(text=df[letter][row], is_correct=False, question=question)
    print("Initial data loaded!")


class Migration(migrations.Migration):
    dependencies = [
        ('masteriqapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
