# Generated by Django 5.0.2 on 2024-03-05 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteriqapp', '0002_auto_20240303_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(through='masteriqapp.IQ', to=settings.AUTH_USER_MODEL),
        ),
    ]
