# Generated by Django 5.0.2 on 2024-03-08 08:23
import os

from django.conf import settings
from django.db import migrations
import glob


def add_category_images(apps, schema_editor):
    category_model = apps.get_model('masteriqapp', 'Category')

    for category in category_model.objects.all():
        directory = settings.IMAGES_FOLDER
        img_name = category.name.lower().replace(' ', '_') + ".*"
        print(img_name)
        f = os.path.join(directory, img_name)
        files = glob.glob(f)
        print("found: " + str(len(files)))
        if len(files) > 0:
            print(files[0])
            category.image_path = os.path.join(files[0])
            category.save()


class Migration(migrations.Migration):
    dependencies = [
        ('masteriqapp', '0005_category_image_path'),
    ]

    operations = [
        migrations.RunPython(add_category_images)
    ]
