# Generated by Django 5.0.2 on 2024-03-14 16:38

from django.db import migrations

def add_community_category(apps, schema_editor):
    category_model = apps.get_model('masteriqapp', 'Category')
    category_model.objects.create(name="Community", image_path='data\\images\\community.jpg')

class Migration(migrations.Migration):

    dependencies = [
        ('masteriqapp', '0004_auto_20240308_0923'),
    ]

    operations = [
        migrations.RunPython(add_community_category)
    ]
