# Generated by Django 5.0.2 on 2024-03-08 08:42
from os import path

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteriqapp', '0002_auto_20240303_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(default=path.join(settings.IMAGES_FOLDER, 'default.jpeg'), max_length=255),
        ),
    ]
